services:
  - type: web
    name: slkwebsite-next
    runtime: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
    autoDeploy: true
    branch: main
